apiVersion: apps/v1
kind: Deployment
metadata:
  name: imsrproject1819-deployment
spec:
  selector:
    matchLabels:
      app: imsrproject1819
  replicas: 1
  template:
    metadata:
      labels:
        app: imsrproject1819
    spec:
      containers:
      - name: imsrproject1819
        image: lackhmipriya/imsrprojectdeploy:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: imsrproject1819-service
spec:
  selector: 
    app: imsrproject1819
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort